### ISSUE TITLE
Stack do projeto?

### ISSUE THREAD

**Issue by henryqrm** [vuejobsbrasil/vuejobsbrasil#1]
Seria interessante ser tudo JS. Node, mongo, nuxt e etc.

**Comment by ErickPetru** [comment]
Sou muito favorável ao Nuxt, estou muito contente com ele (e olha que ainda está em RC!). Sobre o banco e o backend, não tenho uma opinião muito concreta. Gosto da ideia de _full stack_ JavaScript por apreciar a linguagem e o ecossistema, mas isso é mais gosto pessoal do que uma vantagem inquestionável.

**Comment by rubenmarcus** [comment]
Eu posso opinar mais na parte visual e UI, porque ainda manjo muito pouco de Vue. Mas apoio a idéia do Nuxt, e tenho simpatia pelo Firebase.

Precisariamos de um painel CMS né. 

e uma idéia seria fazer um scrapper em  Node e rodar em sites tipo Jooble,Trampos,LoveMondays etc e achar pelo nome "Vue" e jogar pro banco...

**Comment by ErickPetru** [comment]
Nunca usei Firebase na prática, mas a ideia me anima. Coincidentemente estava lendo sobre ele agora neste tutorial: https://medium.com/@anas.mammeri/vue-2-firebase-how-to-build-a-vue-app-with-firebase-authentication-system-in-15-minutes-fdce6f289c3c

**Comment by rubenmarcus** [comment]
Quasar para um app mobile... ? ou Weex ?

**Comment by ErickPetru** [comment]
Acho que app mobile é um passo à frente, não me preocuparia com isso agora. E talvez um PWA atenda (o Nuxt já está trabalhando pra ser tudo PWA sem termos que fazer nada pra isso).

**Comment by henryqrm** [comment]
Acredito que PWA resolva a questão do mobile, estou fazendo meu TCC em cima de PWA com Vue, e é sensacional. Em relação ao Firebase, sou um admirador.

**Comment by rubenmarcus** [comment]
@ErickPetru  sobre usar o código do Vue Jobs original ñ teriamos problemas, pois a idéia inicial do nosso ia ser gratuito até o possivel, e o deles eles não cobram? Teriamos que fazer modificações ou não?

**Comment by henryqrm** [comment]
Sim, teria. Porém acho pouco provável que ele deixe fazer um fork, afinal tem empresas pagando para anunciar e etc.

**Comment by alvarengathomas** [comment]
Fala galera, tenho 1 ano de experiência com VueJS/Vuex em produção, sou contribuidor no repositório do Vuex e vou palestrar sobre "Porque o VueJS está conquistando o desenvolvimento frontend?", no evento frontinvale.com.br e gostaria muito de contribuir nesse projeto!

Além do frontend, tenho experiência com node, express, sequelize, MySQL e etc.

Gosto da ideia do firebase também.

**Comment by Cleysonlb** [comment]
Temos que levar em consideração  tecnologias X tempo!
Curto a ideia de usar full stack javascript, desenvolver usando node e consumindo as API's no Vue seria o ideal!
Sobre o slack :white_check_mark:

**Comment by rubenmarcus** [comment]
hospedar será no heroku então ? Eu quero ajudar na parte de UI e se der algumas views do front também, mas quero aprender a parte de servidor também, firebase ou mongo e node.js, é que atualmente nos 7 anos de front 90% do tempo mexi com UI ,então tenho mais expertise nisso. Mas quero ir mais pro back também

**Comment by ErickPetru** [comment]
Se usar Firebase ou qualquer outra abordagem _serverless_, podemos hospedar o front em qualquer lugar. Tenho um site criado com Nuxt rodando no [surge.sh](http://surge.sh/) de forma muito simples, pois o Nuxt gera todos os arquivos estáticos para subir em qualquer CDN, não precisa de um servidor realmente.

**Comment by alvarengathomas** [comment]
Levando em consideração tecnologias X tempo, nuxt + firebase seria o mais rápido

**Comment by rubenmarcus** [comment]
Criei um projeto no firebase ,aqui. Tem como adicionar mais colaboradores nele? Vamos dividir a equipe em quantos? (2)? (Front e Back) ? acham que precisa de mais gente? E as telas do site vamos definir quais?
Vai ser só uma listagem básica com links, e um que qualquer pessoa poderia postar uma vaga que será aprovada por um admin, ou terá mais coisas?

**Comment by rubenmarcus** [comment]
Alguém quer ser owner comigo aqui? Eu coloquei o e-mail da organização um pessoal meu, mas preciso apontar o servidor do vuejobs.com.br pra algum. No meu bluehost eles dão e-mail. Não sei se vale a pena apontar o dominio todo

**Comment by rubenmarcus** [comment]
Acho que pra um primeiro momento,uma listagem basta, mas num segundo seria legal ter um sistema inteiro mesmo.

**Comment by Cleysonlb** [comment]
Vai ter um formulário onde as empresas preenchem com dados da vaga e a gente recebe por email pra por la no site?!

**Comment by Cleysonlb** [comment]
@ErickPetru o surge.sh é muito bom! Podemos usar ele nesse primeiro momento!

**Comment by rubenmarcus** [comment]
hje a noite vou começar a montar umas telas então e publicar no surge... eu vou ficar fora o feriado, mas domingo a noite to de volta e ai publico aqui no repositório o que fazer hoje

**Comment by alvarengathomas** [comment]
Podemos criar um Slack pra conversar mais diretamente

**Comment by alvarengathomas** [comment]
Criei um slack pra nós, só acessar esse link e pedir um convite:

**Comment by Cleysonlb** [comment]
@alvarengathomas podia criar um grupo de Slack `Vue Brasil` onde a galera pode entrar pra trocar ideia, e criamos um channel privado pra galera do `vuejobs brasil` Oq acham?

**Comment by ErickPetru** [comment]
@Cleysonlb, já há um slack [Vue.js Brasil](https://vuejs-brasil.slack.com/) com vários canais. Imagino que o Daniel Schmitz e o Fabio Vedovelli não se importariam em criar um canal a mais lá.

**Comment by trickstival** [comment]
Galera, eu quero contribuir também para o projeto (já deixei meu nickname lá no grupo do facebook). Tenho alguma experiência com o Firebase, já que estou usando ele no meu TCC, então pra mim seria tranquilo. A única coisa que me deixa com um pé atrás sobre o firebase é em relação às queries serem muito limitadas, então teríamos que usar um Algolia ou ElasticSearch pra criar os índices.

**Comment by omarkdev** [comment]
Tenho interesse também em contribuir com o desenvolvimento desse projeto (e de outros projetos que vamos ter no decorrer) tanto como front ou back, mas a preferencia é back-end.

Acho que a ideia de usarmos uma stack full javascript é sensacional, ou com a api com Laravel, o que acham?

**Comment by trickstival** [comment]
Eu prefiro a ideia do FullStack com Javascript, mas se for optado pelo Laravel vai ser mais conhecimento agregado.

**Comment by rubenmarcus** [comment]
@omarkdev  e @trickstival  add
@ErickPetru  alguma notícia sobre o Vue Jobs americano? se pegarmos o código deles, como ficaria esse lance de monetização que elesq uerem fazeR? Nossa equipe ia manter o projeto com o código deles aqui, e o "lucro", sei lá os ganhos iam pra eles?

**Comment by trickstival** [comment]
Depende Ruben. Se a nossa proposta de escopo do projeto é só fazer uma tradução do site em inglês, acho justo deixar os lucros pra eles. Se estivermos falando de criar um site do zero, podemos começar a falar de algo entre nós.

**Comment by rubenmarcus** [comment]
@trickstival  por manter, eu entendia que iriamos nós revisar as vagas postadas, e meio que melhorar a ferramenta, por exemplo: Testes para devs, estilo hackerank e contratado.me , avaliação de empresas/ vagas estilo Love Mondays, ranking de empresas, especialmente pelo tipo de vagas que postam e por avaliações,a idéia original era acompanhar a carreira de um dev vue, ele tendo um perfil tb, e ajuda-lo a evoluir.

Eu não posso falar do Vue Jobs americano, mas a primeira vista parece uma lista de vagas de vue. Mesmo usando o código deles, acho que dá pra fazer muito mais.

**Comment by rubenmarcus** [comment]
@trickstival  @ErickPetru  mas falando do projeto, se for acertaod que será uma branch do americano, ai tem que ver o que é permitido extender essa branch, e as licenças e etc do que irá ser feito, agora se for do zero, acho justo dividirmos os participantes em times, eu me dou bem com design e queria fazer a parte visual, se algum outro designer quiser colaborar e fazer um projeto em time, eu topo, e a parte das views se puder colaborar tb em algo , vou curtir, enfim, temos que avaliar e delegar a cada um o que fazer

**Comment by trickstival** [comment]
Gosto da ideia de num primeiro a gente fazer o básico de listagem de vagas, assim como o Vue Jobs americano. Digo isso porque imagino que tenha maior facilidade com licenças se fizermos apenas uma "versão brasileira". Se a ideia vingar, podemos aumentar para um sistema completo. O que acham?

**Comment by rubenmarcus** [comment]
@trickstival  acho a idéia boa. Mas temos que esperar o feedback do @ErickPetru

**Comment by ErickPetru** [comment]
Conformei comentei na postagem no Facebook, o Israel Ortuño demonstrou que há bastante interesse por parte deles na expansão do VueJobs atual. Mas confesso que aquelas perguntas sobre o modelo de negócios brasileiro no ramo de vagas de emprego me "quebrou as pernas". Sinceramente não sei responder àquilo e a "negociação" parou.

**Comment by rubenmarcus** [comment]
@ErickPetru  então acha que tocamos o projeto nós mesmos, ou fazemos uma pesquisa pros caras? Eu conheço por cima só, Tem uns focados em cobrar das empresas e usuários (Catho,Linkedin,Trampos etc) e uns só das empresas. 

O proprio VueJobs Americano deve ter um modelo de negócios. Acho que pra esse projeto Brasileiro um dia vai ter que ser pensado nisso ,e todos nós teriamos um salário, caso o projeto virasse legal mesmo. Mas acho que num primeiro momento e segundo até, é no esquema de contribuição mesmo ( falou o cara que não sabe nem cobrar pelos freelas direito kkkk )

**Comment by rubenmarcus** [comment]
Rola de cada vaga do site virar uma Issue desse projeto? Acredito que teria a inscrição online pelo site, mas acho legal fóruns como o Front-endbr/vagas

**Comment by omarkdev** [comment]
@rubenmarcus Acredito que termos um vuejobsbrasil/vagas seria sensacional, e ainda mais, poderiamos fazer toda a interação do site integrado com o GitHub, desde comentar a vaga, submeter a vaga e tudo mais, todo teste para a vaga teria que ser integrado com o github.

**Comment by rubenmarcus** [comment]
Bom galera, podemos então ver se vamos ser branch do Vue Jobs americano, ou começar o projeto aqui e começar a distribuir as tarefas, e realmente iniciar o projeto.

**Comment by trickstival** [comment]
A gente vai fazer essa decisão no estilo voto Ruben?

**Comment by trickstival** [comment]
Eu sou a favor de começarmos um projeto do zero mas estabelecermos boas relações com o Vue Jobs americano, como uma via de mão dupla. O que acham? Assim dá pra eles ficarem por dentro do que a gente está planejando e a gente age de forma colaborativa.

**Comment by omarkdev** [comment]
Apoio também começarmos um projeto um projeto do zero e votarmos em um Stack

**Comment by GabrielBibiano** [comment]
Opa, galera! Desculpem a demora. Já trabalhei com Vue em produção e estou dando meus primeiros passos em Vuex. Trabalho também com Node e acredito que seria uma ótima opção pro back, como já foi falado

**Comment by ErickPetru** [comment]
Galera, conversei um pouco mais com os caras do VueJobs internacional e eles se posicionaram favoráveis e muito empolgados com uma expansão do serviço para a Brasil. Eles informaram que precisam de alguns dias apenas para planejarem um pouco como isso seria feito de forma prática, como a questão do código-fonte, separação ou não dos dados, essas coisas. Avisarei novamente quando tiver algo concreto. Se, enquanto isso, vocês preferem começar a implementar algo por conta, fiquem à vontade, mas pretendo esperar a posição oficial deles, pois acredito fortemente que uma comunidade integrada internacionalmente é muito melhor do que uma ação brasileira isolada.

**Comment by rubenmarcus** [comment]
Qual o intuito de vocês de fazerem esse projeto? O meu era dois, começar a trabalhar com vue e aprender mesmo, e conseguir um freela / job com vue também. Eu estou meio focado nos estudos e conseguir trabalhar remoto. Não queria pra agora, poderia ser pra Janeiro por exemplo, mas eu me vejo muito mais dedicando meu tempo ao vue do que Angular e React por exemplo, que também quero aprender, mas não me aprofundar

**Comment by trickstival** [comment]
O meu objetivo com o projeto é aprender e me divertir. Programar é algo que eu acho muito legal, e o Vue torna isso muito mais interessante. Se a gente conseguir tirar algum tipo de renda desse projeto, ótimo, seria muito legal. Mas como eu ainda não tenho experiência profissional, tô terminando o ensino médio agora (tenho 16 anos) e quero contribuir pra comunidade do Vue.js ganhando essa experiência, o projeto vai ser ótimo pra mim.

**Comment by tghelere** [comment]
Galera que não está no slack, estamos organizando um hangout para hj, 20h

**Comment by omarkdev** [comment]
Não irei poder participar do hangout.

Eu acho que deviamos criar um projeto apenas nosso e não usar o projeto americano, poque acho que seria interessante ter o projeto como Open Source, se isso for uma possibilidade, provavelmente será um problema disponibilizar o código fonte deles, já que em uma pesquisa rápida, aparentemente o projeto não é Open Source.

**Comment by rubenmarcus** [comment]
Galera estou fechando essa Issue, por favor comentem qualquer sugestão, em uma das issues já abertas, ou na de "sugestões do projeto" , e seriam sugestões ou opiniões gerais sobre o projeto, qualquer comentário vale.

Resolvi iniciar a organização do projeto pelo git mesmo, sem trello ou asana, usando cards no [zenhub](https://www.zenhub.com/) , tentem instalar no navegador de vocês e ver se funciona o link para boards, e se conseguem interagir qualquer coisa, entre em contato no [slack](https://vuejobsbrasil.slack.com/) do projeto, ou nessa [**issue**](https://github.com/vuejobsbrasil/vuejobsbrasil/issues/7).

Obrigado.
